# Generated by Django 5.1.4 on 2025-01-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_cartmodel_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
