# Generated by Django 5.1.4 on 2025-01-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_cartmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='Date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
