# Generated by Django 5.1.4 on 2025-01-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_cartmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='Quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
