# Generated by Django 5.1.4 on 2025-01-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_profilemodel_delete_reviewmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={},
        ),
        migrations.AlterModelManagers(
            name='profilemodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='username',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='User',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=13),
        ),
    ]
