# Generated by Django 5.1.4 on 2025-01-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_profilemodel_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='OrderDate',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
